### PR TITLE
Updated the ProductCard with typechecking and more

### PR DESCRIPTION
**Pull request by ilavisharma**
Changes made to the ProductCard

1. Removed default buttonText prop (buy now)
2. Added renderButton method to render the link/button if the prop is provided
3. Added proptypes to the ProductCard for better typechecking

and also updated the Readme file

### CODE REVIEW

**Comment by nukeop** [comment]
Nic, thanks for contribution. Could you remove the lock files too before merging?

**Comment by ilavisharma** [comment]
Thanks.
Just deleted the lock file (my bad I forgot to gitignore that) 
And it would be great if you publish these changes to npm too.

**Comment by nukeop** [comment]
There's also the yarn.lock file. I'll publish right after merging.

**Comment by ilavisharma** [comment]
Any updates about merging and publishing to npm

**Comment by nukeop** [comment]
Yep like I said, you only need to remove package-lock.json

**Comment by ilavisharma** [comment]
> Yep like I said, you only need to remove package-lock.json

I've already done that

**Comment by nukeop** [comment]
It's still in "files changed" tab though.

**Comment by ilavisharma** [comment]
> It's still in "files changed" tab though.
Of course it is,  because it has been deleted by me
Checkout my master branch from above both lock filed have now been removed

**Comment by nukeop** [comment]
Ok, I just published it.

**Pull request merged**
