### PR TITLE
Support tags at News Card

### PR DESCRIPTION
**Pull request by fogfish**

### CODE REVIEW

**Comment by nukeop** [comment]
Nice.
Why did you add a pre-built bundle though?

**Comment by nukeop** [comment]
Ah, I get it, you don't want to use npm. I guess if you need that for some reason, you could add it to the travis config file so it's always up to date.

**Comment by nukeop** [comment]
I finally had the time to review and test your changes. Thanks for the PR, I'll publish now.

**Comment by fogfish** [comment]
Great! Thank! Please drop me a message when `npm` package is published. I'll migrate my staff to it.

**Pull request merged**
